<?

if ($page=='fmanager') {include("modul/filemanager/main.php"); $include=1;}
else if ($page=='news'){include("modul/news/main.php"); $include=1;}
else if ($page=='add_news'){include("modul/news/add_news.php"); $include=1;}
else if ($page=='formmanager'){include("modul/formmanager/main.php"); $include=1;}
else if ($page=='materials'){include("modul/materials/main.php"); $include=1;}
else if ($page=='add_folder_materials'){include("modul/materials/add_folder_materials.php"); $include=1;}
else if ($page=='add_pages'){include("modul/materials/add_pages.php"); $include=1;}
else if ($page=='katalog'){include("modul/katalog/main.php"); $include=1;}
else if ($page=='add_folder_katalog'){include("modul/katalog/add_folder_katalog.php"); $include=1;}
else if ($page=='add_goods'){include("modul/katalog/add_goods.php"); $include=1;}
else if ($page=='goods_stamp'){include("modul/katalog/goods_stamp.php"); $include=1;}
else if ($page=='goods_harakteristiki'){include("modul/katalog/goods_harakteristiki.php"); $include=1;}
else if ($page=='add_cat_harakteristika'){include("modul/katalog/add_cat_harakteristika.php"); $include=1;}
else if ($page=='harakter_all'){include("modul/katalog/harakter_all.php"); $include=1;}
else if ($page=='goods_firms'){include("modul/katalog/goods_firms.php"); $include=1;}
else if ($page=='goods_price'){include("modul/katalog/goods_price.php"); $include=1;}
else if ($page=='goods_newprice'){include("modul/katalog/goods_newprice.php"); $include=1;}
else if ($page=='yml'){include("modul/katalog/yml.php"); $include=1;}
else if ($page=='goods_zakaz'){include("modul/katalog/zakaz.php"); $include=1;}
else if ($page=='inf_zakaz'){include("modul/katalog/inf_zakaz.php"); $include=1;}
else if ($page=='kupon'){include("modul/kupon/main.php"); $include=1;}
else if ($page=='add_kupon'){include("modul/kupon/add_kupon.php"); $include=1;}
else if ($page=='goods_export'){include("modul/synchronization/main.php"); $include=1;}
else if ($page=='config'){include("modul/settings/main.php"); $include=1;}
else if ($page=='vnedrenie'){include("modul/settings/vnedrenie.php"); $include=1;}
else if ($page=='moduls'){include("modul/settings/moduls.php"); $include=1;}
else if ($page=='license'){include("modul/settings/license.php"); $include=1;}
else if ($page=='main_adm'){include("modul/settings/main_adm.php"); $include=1;}
else if ($page=='admin_contacts'){include("modul/settings/admin_contacts.php"); $include=1;}
else if ($page=='users'){include("modul/settings/users.php"); $include=1;}
else if ($page=='add_users'){include("modul/settings/add_users.php"); $include=1;}
else if ($page=='user_inf'){include("modul/settings/user_inf.php"); $include=1;}
else if ($page=='dostup'){include("modul/settings/dostup.php"); $include=1;}
else if ($page=='domain'){include("modul/settings/domain.php"); $include=1;}
else if ($page=='statistika_cms'){include("modul/settings/statistika_cms.php"); $include=1;}
else if ($page=='config_magazin'){include("modul/settings/config_magazin.php"); $include=1;}
else if ($page=='arhiv'){include("modul/arhiv/main.php"); $include=1;}
else if ($page=='antivir'){include("modul/antivir/main.php"); $include=1;}
else if ($page=='zayvki'){include("modul/zayvki/main.php"); $include=1;}
else if ($page=='zayvka_inf'){include("modul/zayvki/zayvka_inf.php"); $include=1;}
else if ($page=='obr_svyz'){include("modul/obr_svyz/main.php"); $include=1;}
else if ($page=='obr_svyz_inf'){include("modul/obr_svyz/obr_svyz_inf.php"); $include=1;}
else if ($page=='galery'){include("modul/galery/main.php"); $include=1;}
else if ($page=='add_galery_cat'){include("modul/galery/add_galery_cat.php"); $include=1;}
else if ($page=='galery_img'){include("modul/galery/galery_img.php"); $include=1;}
else if ($page=='comment'){include("modul/comment/main.php"); $include=1;}
else if ($page=='vopros_otvet'){include("modul/vopros_otvet/main.php"); $include=1;}
else if ($page=='otziv'){include("modul/otziv/main.php"); $include=1;}
else if ($page=='rassilka'){include("modul/rassilka/main.php"); $include=1;}
else if ($page=='statistika'){include("modul/statistika/main.php"); $include=1;}
else if ($page=='stat_zakaz'){include("modul/statistika/stat_zakaz.php"); $include=1;}
else if ($page=='search_site'){include("blocks/search_site.php"); $include=1;}
else if ($page=='zadaniy'){include("modul/zadaniy/main.php"); $include=1;}
else if ($page=='zadaniy_inf'){include("modul/zadaniy/zadaniy_inf.php"); $include=1;}
else {include("modul/desktop/main.php"); $include=1;} 
?>